/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author KARINA
 */
public class MenuHalamanUtamaMhs extends javax.swing.JFrame {

    /**
     * Creates new form MenuHalamanUtamaMhs
     */
    public MenuHalamanUtamaMhs() {
        initComponents();
    }

    public JButton getButtonkeluar() {
        return buttonkeluar;
    }

    public JButton getButtonliat() {
        return buttonliat;
    }

    public JButton getButtonpilih() {
        return buttonpilih;
    }
    public void addListener(ActionListener a){
        buttonkeluar.addActionListener(a);
        buttonliat.addActionListener(a);
        buttonpilih.addActionListener(a);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonliat = new javax.swing.JButton();
        buttonpilih = new javax.swing.JButton();
        buttonkeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonliat.setText("Lihat Info Geladi");
        buttonliat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonliatActionPerformed(evt);
            }
        });

        buttonpilih.setText("Pilih Lokasi Geladi");
        buttonpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpilihActionPerformed(evt);
            }
        });

        buttonkeluar.setText("Log Out");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Halaman Utama Mahasiswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonliat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonpilih, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(buttonkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonliat)
                .addGap(18, 18, 18)
                .addComponent(buttonpilih)
                .addGap(18, 18, 18)
                .addComponent(buttonkeluar)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonliatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonliatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonliatActionPerformed

    private void buttonpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonpilihActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonkeluar;
    private javax.swing.JButton buttonliat;
    private javax.swing.JButton buttonpilih;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
